In [3]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install gym


## Importing the packages

In [4]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

## Creating the Environment

In [5]:
env = gym.make("FrozenLake-v0")

## Creating the Q-Table

In [6]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [7]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Initialising Q-Learning Parameters

In [17]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

## Coding the Q-learning algorithm training loop

In [18]:
rewards_all_episodes = []

In [19]:
# Q-learning algorithm
for episode in range(num_episodes):
    # initialize new episode params
    state = env.reset()
    done = False
    rewards_current_episode = 0
    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        # Take new action
        new_state, reward, done, info = env.step(action)
        # Update Q-table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
        learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        # Set new state
        state = new_state
        # Add new reward        
        rewards_current_episode += reward
        if done == True: 
            break
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    # Add current episode reward to total rewards list
    rewards_all_episodes.append(rewards_current_episode)

## Calculate and print the average reward per thousand episodes

In [20]:
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.05300000000000004
2000 :  0.21100000000000016
3000 :  0.3920000000000003
4000 :  0.5340000000000004
5000 :  0.6420000000000005
6000 :  0.6650000000000005
7000 :  0.6540000000000005
8000 :  0.6700000000000005
9000 :  0.6630000000000005
10000 :  0.6930000000000005


## Print Updated Q-Table

In [21]:
print("\n\n********Q-table********\n")
print(q_table)




********Q-table********

[[0.54970606 0.52147359 0.52637434 0.51404005]
 [0.37860557 0.30614884 0.2870732  0.51275984]
 [0.39388187 0.37895207 0.38666408 0.4871587 ]
 [0.27913376 0.2741006  0.27231159 0.45586151]
 [0.57285907 0.31154304 0.3577769  0.28808962]
 [0.         0.         0.         0.        ]
 [0.19506886 0.20222533 0.34467578 0.15320725]
 [0.         0.         0.         0.        ]
 [0.45248613 0.40875721 0.41118589 0.61456735]
 [0.45289114 0.7067178  0.47181962 0.39405361]
 [0.66997341 0.38442318 0.45067557 0.37565724]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.51239481 0.60069624 0.81085949 0.51497574]
 [0.72860922 0.90212385 0.74129627 0.77468969]
 [0.         0.         0.         0.        ]]
