In [24]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install gym[atari]


    100% |████████████████████████████████| 28.2MB 339kB/s ta 0:00:011
    100% |████████████████████████████████| 2.8MB 2.5MB/s ta 0:00:011


## Importing the packages

In [3]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

## Creating the Environment

In [4]:
env = gym.make("FrozenLake-v0")

## Creating the Q-Table

In [5]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [6]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Initialising Q-Learning Parameters

In [14]:
num_episodes = 100000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

## Coding the Q-learning algorithm training loop

In [15]:
rewards_all_episodes = []

In [16]:
# Q-learning algorithm
for episode in range(num_episodes):
    # initialize new episode params
    state = env.reset()
    done = False
    rewards_current_episode = 0
    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        # Take new action
        new_state, reward, done, info = env.step(action)
        # Update Q-table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
        learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        # Set new state
        state = new_state
        # Add new reward        
        rewards_current_episode += reward
        if done == True: 
            break
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    # Add current episode reward to total rewards list
    rewards_all_episodes.append(rewards_current_episode)

## Calculate and print the average reward per thousand episodes

In [17]:
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.05600000000000004
2000 :  0.20200000000000015
3000 :  0.4120000000000003
4000 :  0.5540000000000004
5000 :  0.6400000000000005
6000 :  0.6550000000000005
7000 :  0.6690000000000005
8000 :  0.7080000000000005
9000 :  0.6960000000000005
10000 :  0.6550000000000005
11000 :  0.6720000000000005
12000 :  0.6790000000000005
13000 :  0.6790000000000005
14000 :  0.6840000000000005
15000 :  0.6520000000000005
16000 :  0.6950000000000005
17000 :  0.6950000000000005
18000 :  0.6820000000000005
19000 :  0.6820000000000005
20000 :  0.6820000000000005
21000 :  0.6860000000000005
22000 :  0.7150000000000005
23000 :  0.6650000000000005
24000 :  0.6920000000000005
25000 :  0.6910000000000005
26000 :  0.6680000000000005
27000 :  0.6770000000000005
28000 :  0.6740000000000005
29000 :  0.6900000000000005
30000 :  0.6580000000000005
31000 :  0.6920000000000005
32000 :  0.6870000000000005
33000 :  0.6740000000000005
34000 :  0.6910000000000005
3

## Print Updated Q-Table

In [11]:
print("\n\n********Q-table********\n")
print(q_table)




********Q-table********

[[0.55269784 0.50553472 0.50682085 0.49044183]
 [0.27463951 0.34778705 0.23572783 0.42958499]
 [0.35796266 0.23771678 0.30866171 0.25568589]
 [0.15763271 0.07086018 0.00906744 0.08659856]
 [0.56203893 0.39069814 0.45704476 0.4470313 ]
 [0.         0.         0.         0.        ]
 [0.29868685 0.12475038 0.16635737 0.11847088]
 [0.         0.         0.         0.        ]
 [0.31509875 0.38263667 0.27869605 0.58844294]
 [0.4941522  0.66413006 0.47004997 0.30682567]
 [0.67545811 0.37097555 0.30006806 0.40181266]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.48744056 0.59465846 0.76997984 0.40277616]
 [0.75077922 0.86321888 0.74784245 0.76289645]
 [0.         0.         0.         0.        ]]


## Watching the agent play the game

In [18]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(11):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):        
        # Show current state of environment on screen
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        # Choose action with highest Q-value for current state
        action = np.argmax(q_table[state,:])
        # Take new action
        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                # Agent reached the goal and won episode
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                # Agent stepped in a hole and lost episode
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            break
        # Set new state
        state = new_state
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
